{{- include "adp-helm-library.deployment" (list . "rpa-mit-notification.deployment") -}}
{{- define "rpa-mit-notification.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "rpa-mit-notification.container") }}
{{- end -}}