version: '3.8'

services:
  rpa-mit-payment:
    image: rpa-mit-payment-development
    container_name: rpa-mit-payment-developer
    ports:
      - "3001:80"
    volumes:
      - ./EST.MIT.Payment.Function:/home/dotnet/EST.MIT.Payment.Function
      - ./EST.MIT.Payment.Function.Tests:/home/dotnet/EST.MIT.Payment.Function.Tests