version: '3.8'

services:
  rpa-mit-payment:
    build:
      context: .
    image: rpa-mit-payment
    container_name: rpa-mit-payment
    ports:
      - 3000:80
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
      AzureWebJobsStorage: ${AzureWebJobsStorage}
      QueueConnectionString: ${QueueConnectionString}
      EventQueueName: ${EventQueueName}
      PaymentQueueName: ${PaymentQueueName}
      Schemes: ${Schemes}
      PaymentHubQueueName: ${PaymentHubQueueName}
      AzureWebJobsSecretStorageType: files
