environment: development
name: est-mit-payment
namespace: ffc-rpa
workstream: ffc-rpa
image: est-mit-payment

labels: {}

azureIdentity:
  resourceID: dummy
  clientID: dummy

appInsights:
  connectionString:

containerConfigMap:
  name: est-mit-payment-config-map

containerSecret:
  name: est-mit-payment-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  imagePullSecret:

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 5m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000
  azureWebJobsStorage: secret
  comPlusEnableDiagnostics: 0
  serviceBusConnectionString__fullyQualifiedNamespace: SNDFFCINFSB1001.servicebus.windows.net
  serviceBusConnectionString__credential: managedidentity
  serviceBusQueueName: rpa-mit-payment
  queueConnectionString__queueServiceUri: https://sndffcrpamitst1001.queue.core.windows.net/
  queueConnectionString__credential: managedidentity
  eventQueueName: rpa-mit-events
  paymentQueueName: rpa-mit-payment
  
volumeMounts:
  mountPath: /var/www/
  name: core-app-dir

aadPodIdentity: true