{{- include "ffc-helm-library.container-config-map" (list . "est-mit-payment.config-map") -}}
{{- define "est-mit-payment.config-map" -}}
data:
  COMPlus_EnableDiagnostics: {{ .Values.container.comPlusEnableDiagnostics | quote }}
  PORT: {{ .Values.container.port | quote }}
  QueueConnectionString__queueServiceUri: {{ quote .Values.container.queueConnectionString__queueServiceUri }}
  QueueConnectionString__credential: {{ quote .Values.container.queueConnectionString__credential }}
  ServiceBusConnectionString__fullyQualifiedNamespace: {{ quote .Values.container.serviceBusConnectionString__fullyQualifiedNamespace }}
  ServiceBusConnectionString__credential: {{ quote .Values.container.serviceBusConnectionString__credential }}
  ServiceBusQueueName: {{ .Values.container.serviceBusQueueName }}
  EventQueueName: {{ .Values.container.eventQueueName }}
  PaymentQueueName: {{ .Values.container.paymentQueueName }}
{{- end -}}